const titles=['Settings','Units & commanders','Raptors & customs','Epics & economy','Factories & launchers'];
let state={edits:{},lua:{},fields:{},raptorHP:2,queenHP:2};
try { const saved=JSON.parse(localStorage.getItem('nutty-config-v1'));if(saved)state={...state,...saved}; }catch{}
const copied=new Map();let active=0;const sources={};const fields={};
BASE_PARTS.forEach((p,pi)=>p.commands.forEach((c,ci)=>{const m=c.match(/^!bset (tweak\w+) (\S+)$/i);if(m&&m[2]!=='0'){const key=pi+'/'+ci;sources[key]=decodeLua(m[2]);fields[key]=numericFields(sources[key]);}}));
function save(){try{localStorage.setItem('nutty-config-v1',JSON.stringify(state));}catch{}refreshOutput();}
function luaFor(key){const raw=state.lua[key]??replaceFields(sources[key],fields[key],state.fields[key]||{});return /^--HP_2X_QHP_2X/.test(raw)?hpSource(raw,state.raptorHP,state.queenHP):raw;}
function command(pi,ci){const key=pi+'/'+ci;let c=state.edits[key]??BASE_PARTS[pi].commands[ci];if(sources[key])c=c.match(/^!bset \w+ /i)[0]+encodeLua(luaFor(key));if(c.startsWith('$rename '))c=c.replace(/\[Qx[^\]]+\]/,'[Qx'+queenCount()+']').replace(/\[[^\]]+xQHP\]/,'['+state.queenHP+'xQHP]').replace(/\[[^\]]+xRHP\]/,'['+state.raptorHP+'xRHP]');return c;}
function queenCount(){for(let i=0;i<BASE_PARTS[0].commands.length;i++){const c=state.edits['0/'+i]??BASE_PARTS[0].commands[i];const m=c.match(/^!bset raptor_queen_count (\d+)/i);if(m)return m[1];}return 100;}
function label(c){const m=c.match(/^!bset (tweak\w+) (\S+)$/i);if(m&&m[2]!=='0')return m[1]+' · '+decodeLua(m[2]).split('\n')[0].replace(/^--/,'').replaceAll('_',' ');return c;}
async function copyText(text,button,key){let ok=false;try{await navigator.clipboard.writeText(text);ok=true;}catch{const manual=document.getElementById('manual');manual.hidden=false;manual.value=text;manual.focus();manual.select();try{ok=document.execCommand('copy');}catch{}if(ok)manual.hidden=true;}
if(ok){if(key)copied.set(key,text);button.textContent='Copied ✓';document.getElementById('status').textContent='Copied. Paste into BAR lobby chat and press Enter.';}else document.getElementById('status').textContent='Press Ctrl+C to copy the selected text below.';}
function rangeFor(name,value){if(name==='raptor_queen_count')return [1,100,1];if(name.startsWith('start'))return [0,1000000,1000];if(name.includes('multiplier')||name.endsWith('mult'))return [0,Math.max(10,value*2),0.1];if(name==='maxunits')return [100,50000,100];if(name==='teamsize')return [1,32,1];if(name==='health'||name.includes('cost')||name==='buildtime')return [0,Math.max(100,value*3),Math.max(1,Math.floor(value/100))];if(name==='reloadtime'||name==='burstrate')return [0.01,Math.max(10,value*3),0.01];return [Math.min(0,value),Math.max(10,value*3),Number.isInteger(value)?1:0.01];}
function numericControl(parent,name,value,onChange,range){const wrap=document.createElement('div');wrap.className='control';const title=document.createElement('label');const id='number-'+(++numericControl.next);title.htmlFor=id;title.textContent=name;const inputs=document.createElement('div');inputs.className='inputs';const slider=document.createElement('input');slider.type='range';const number=document.createElement('input');number.type='number';number.id=id;number.setAttribute('aria-label',name+' value');slider.setAttribute('aria-label',name+' slider');const [min,max,step]=range||rangeFor(name,value);slider.min=min;slider.max=max;slider.step=step;slider.value=value;number.step=step;number.value=value;number.min=min;number.max=Math.max(max,value);function update(from,to){const v=Number(from.value);if(!Number.isFinite(v)||from.value==='')return;if(v<min){from.setCustomValidity('Minimum '+min);return;}from.setCustomValidity('');if(v>Number(slider.max))slider.max=v;number.max=Math.max(Number(number.max),v);to.value=v;onChange(v);}slider.addEventListener('input',()=>update(slider,number));number.addEventListener('input',()=>update(number,slider));inputs.append(slider,number);wrap.append(title,inputs);parent.append(wrap);}
numericControl.next=0;
function settings(){const root=document.getElementById('settings');root.replaceChildren();const hp=document.createElement('div');hp.className='grid';numericControl(hp,'Raptor health multiplier',state.raptorHP,v=>{state.raptorHP=v;save();},[0.1,10,0.1]);numericControl(hp,'Queen health multiplier',state.queenHP,v=>{state.queenHP=v;save();},[0.1,10,0.1]);root.append(hp);const grid=document.createElement('div');grid.className='grid';root.append(grid);BASE_PARTS[0].commands.forEach((base,i)=>{if(/^!bset tweak/i.test(base)||base==='!balance')return;const key='0/'+i;const c=state.edits[key]??base;const m=c.match(/^(!\S+\s+(?:\S+\s+)?)(-?\d+(?:\.\d+)?)$/);const simple=c.match(/^(!\S+)\s+(-?\d+(?:\.\d+)?)$/);const bset=c.match(/^(!bset\s+\S+)\s+(-?\d+(?:\.\d+)?)$/i);const number=simple||bset;if(number){const prefix=number[1];const name=prefix.replace(/^!bset\s+/i,'').replace(/^!/,'');const bool=Number(number[2])<=1&&/^(disablemapdamage|experimentalextraunits|experimentallegionfaction|releasecandidates|scavunitsforplayers|forceallunits|unit_|evocom)/.test(name);if(!bool){numericControl(grid,name,Number(number[2]),v=>{state.edits[key]=prefix+' '+v;save();});return;}}
const control=document.createElement('div');control.className='control';const lab=document.createElement('label');lab.textContent=c.split(' ').slice(0,bset?2:1).join(' ');const field=document.createElement('input');field.type='text';field.value=c;field.setAttribute('aria-label',lab.textContent+' command');field.addEventListener('change',()=>{if(!field.value.trim()||/[\r\n]/.test(field.value)){field.setCustomValidity('Enter one command');field.reportValidity();return;}field.setCustomValidity('');state.edits[key]=field.value;save();});control.append(lab,field);grid.append(control);});}
function render(index){active=index;const container=document.getElementById('commands');container.replaceChildren();document.querySelectorAll('#tabs button').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',i===index);});BASE_PARTS[index].commands.forEach((base,i)=>{const key=index+'/'+i;const row=document.createElement('section');row.className='row';const head=document.createElement('div');head.className='row-head';const title=document.createElement('div');title.className='title';title.textContent=(i+1)+'. '+label(base);const button=document.createElement('button');button.textContent=copied.get(key)===command(index,i)?'Copied ✓':'Copy command';button.addEventListener('click',()=>copyText(command(index,i),button,key));head.append(title,button);row.append(head);const preview=document.createElement('textarea');preview.readOnly=true;preview.className='preview';preview.dataset.key=key;preview.setAttribute('aria-label',label(base)+' generated command');row.append(preview);if(sources[key]){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Adjust unit values ('+fields[key].length+')';details.append(summary);details.addEventListener('toggle',()=>{if(!details.open||details.dataset.loaded)return;details.dataset.loaded='yes';const grid=document.createElement('div');grid.className='grid';fields[key].forEach((f,fi)=>numericControl(grid,f.section+' · '+(f.context?f.context+' · ':'')+f.name,Number(state.fields[key]?.[fi]??f.value),v=>{delete state.lua[key];state.fields[key]??={};state.fields[key][fi]=v;save();},rangeFor(f.name,f.value)));details.append(grid);});row.append(details);const advanced=document.createElement('details');const sum=document.createElement('summary');sum.textContent='Advanced: edit complete Lua';advanced.append(sum);const editor=document.createElement('textarea');editor.className='lua';editor.value=luaFor(key);editor.setAttribute('aria-label',label(base)+' Lua source');const apply=document.createElement('button');apply.textContent='Apply Lua edits';apply.addEventListener('click',()=>{state.lua[key]=editor.value;state.fields[key]={};save();document.getElementById('status').textContent='Lua updated. Custom Lua edits require in-game testing.';render(active);});advanced.append(editor,apply);row.append(advanced);}container.append(row);});refreshOutput();}
function refreshOutput(){document.querySelectorAll('.preview').forEach(el=>{const [p,c]=el.dataset.key.split('/').map(Number);const next=command(p,c);el.value=next;const button=el.closest('.row').querySelector('button');button.textContent=copied.get(el.dataset.key)===next?'Copied ✓':'Copy command';});document.getElementById('copy-part').textContent='Copy part '+(active+1);}
titles.forEach((title,i)=>{const b=document.createElement('button');b.textContent=(i+1)+' · '+title;b.addEventListener('click',()=>render(i));document.getElementById('tabs').append(b);});
document.getElementById('copy-part').addEventListener('click',e=>copyText(BASE_PARTS[active].commands.map((_,i)=>command(active,i)).join('\n'),e.target));
document.getElementById('reset').addEventListener('click',()=>{state={edits:{},lua:{},fields:{},raptorHP:2,queenHP:2};copied.clear();save();settings();render(active);document.getElementById('status').textContent='Restored your original settings and prepared Starfall fix.';});
document.getElementById('download').addEventListener('click',()=>{const text=BASE_PARTS.flatMap((p,pi)=>p.commands.map((_,ci)=>command(pi,ci))).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download='nuttyb-custom.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
settings();render(0);
